In [1]:
import numpy as np

In [1]:
import numpy as np

## 5. Calculate Total and Average quantities sold

In [28]:
# Each column is is specific product (we have 4 products )
# Each row is specific order  (we have 2 orders)
order_quantities = np.array([[5,3,2,7],[10,6,3,9]])
print(f"Each column is is specific product - Each row is specific order :  \n{order_quantities}")

Each column is is specific product - Each row is specific order :  
[[ 5  3  2  7]
 [10  6  3  9]]


In [29]:
# Quantities of the sales per product
total_quantities_sold_per_product = np.sum(order_quantities,axis = 0)
print(f"Quantities of the sales per product: {total_quantities_sold_per_product}")

Quantities of the sales per product: [15  9  5 16]


In [30]:
# Quantities of the sales per order
total_quantities_sold_per_order = np.sum(order_quantities,axis = 1)
print(f"Quantities of the sales per order: {total_quantities_sold_per_order}")

Quantities of the sales per order: [17 28]


In [31]:
# Average guantities per product across all orders
average_quantities_sold_per_product = np.mean(order_quantities,axis = 0)
print(f"Average guantities per product across all orders: {average_quantities_sold_per_product}")

Average guantities per product across all orders: [7.5 4.5 2.5 8. ]


## 6. Calculate Average product Rating and Maximum rating per Category

In [38]:
#Each row is one pproduct
#Each product is rated in 4 categories
product_ratings = np.array([
    [4.5,3.2,2.5,5.0],
    [4.3,3.8,1.0,4.8],
    [2.0,3.6,4.7,0.5]
])
product_ratings

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [41]:
average_rating_per_category = np.mean(product_ratings,axis=0)
print(f"Average rating for each category {average_rating_per_category}")

Average rating for each category [3.6        3.53333333 2.73333333 3.43333333]


In [41]:
average_rating_per_category = np.mean(product_ratings,axis=0)
print(f"Average rating for each category {average_rating_per_category}")

Average rating for each category [3.6        3.53333333 2.73333333 3.43333333]


In [44]:
maximum_rating_per_category = np.max(product_ratings,axis=0)
print(f"Maximum rating for each product {maximum_rating_per_category}")

Maximum rating for each product [4.5 3.8 4.7 5. ]
