In [1]:
import numpy as np

## 1. Calculating Total Revenue

In [3]:
prices = np.array([19.99,29.99,14.99,9.99,24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [4]:
quantities=np.array([10,5,8,12,3])
quantities

array([10,  5,  8, 12,  3])

In [5]:
revenue_per_product = prices*quantities
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [6]:
total_revenue = np.sum(revenue_per_product)
total_revenue

np.float64(664.62)

## 2. Analyzing Blog Post Stats

In [8]:
views = np.array([1000,500,800,1200,300,600])
views

array([1000,  500,  800, 1200,  300,  600])

In [9]:
max_views = np.max(views)
max_views

np.int64(1200)

In [10]:
min_views = np.min(views)
min_views

np.int64(300)

In [11]:
average_views = np.average(views)
average_views

np.float64(733.3333333333334)

In [12]:
total_views = np.sum(views)
total_views

np.int64(4400)

## 3. Splitting Order into Batches

In [17]:
oder_ids = np.array([1001,1002,1003,1004,1005,1006,1007,1008])
oder_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])

In [18]:
batches = np.split(oder_ids, 4)
batches

[array([1001, 1002]),
 array([1003, 1004]),
 array([1005, 1006]),
 array([1007, 1008])]

In [21]:
# Итерация по массиву
for batch in batches: 
    print(batch)

[1001 1002]
[1003 1004]
[1005 1006]
[1007 1008]


In [24]:
# Итерация по массиву по индексу
for batch in batches: 
    print("First element in the batch",batch[0])
    print("Second element in the batch",batch[1])

First element in the batch 1001
Second element in the batch 1002
First element in the batch 1003
Second element in the batch 1004
First element in the batch 1005
Second element in the batch 1006
First element in the batch 1007
Second element in the batch 1008


In [32]:
for i , batch in enumerate(batches): 
    print(f"Batch number {i}: ")
    print("First element in the batch: ",batch[0])
    print("Second element in the batch: ",batch[1])
    print('')

Batch number 0: 
First element in the batch:  1001
Second element in the batch:  1002

Batch number 1: 
First element in the batch:  1003
Second element in the batch:  1004

Batch number 2: 
First element in the batch:  1005
Second element in the batch:  1006

Batch number 3: 
First element in the batch:  1007
Second element in the batch:  1008



## 4. Categorizing Product Ratings

In [33]:
ratings = np.array([4.5,3.2,2.8,5.0,4.1,3.9,2.5,4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 2.5, 4.7])

In [34]:
positive_ratings = ratings[ratings>=4.0]
positive_ratings

array([4.5, 5. , 4.1, 4.7])

In [36]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.2, 2.8, 3.9, 2.5])