In [1]:
import numpy as np

In [6]:
first = np.array([[1,2,3],[4,5,6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
first.shape

(2, 3)

In [8]:
first.ndim

2

In [10]:
second = np.array([[7,8,9],[10,11,12]])
second

array([[ 7,  8,  9],
       [10, 11, 12]])

In [11]:
second.shape

(2, 3)

In [14]:
third = first + second

In [13]:
first + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [15]:
third

array([[ 8, 10, 12],
       [14, 16, 18]])

In [17]:
four=first / 3

In [18]:
four

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])